### ISSUE TITLE
"Automatically switch off Yubikey" turns on Yubikey after lockscreen

### ISSUE THREAD

**Issue by WilliamYuhangLee** [pallotron/yubiswitch#104]
Issue: if the "Automatically switch off Yubikey" option is selected, and the Yubikey is manually disabled (before it is automatically switched off), and the laptop locks screen/sleeps, when it wakes up, the Yubikey will be re-enabled, despite the "Enable Yubikey when system locks/sleeps" is not checked.

Reproduction: 
1. Turn all the settings off
2. Enable the "Automatically switch off Yubikey" option
3. Enable the Yubikey manually (if it is not already enabled)
4. Disable the Yubikey manually (before the Yubikey is automatically switched off after certain amount of time determined by preferences setting)
5. Lock the screen / make the laptop sleeps
6. Wake up the laptop and login
7. Now the Yubikey is enabled again, despite the user having not asked it to

**Comment by likethesky** [comment]
I believe https://github.com/pallotron/yubiswitch/pull/108 fixes this issue. I've made a friendly ping to @pallotron to see if he has an M1 Mac now and is able to build new binaries with that PR from @reaperhulk incorporated. Fingers crossed!

**Comment by davidrothera** [comment]
I am unable to repro with v0.14, @WilliamYuhangLee please update to the new version and re-open if you are still seeing this issue.
