### ISSUE TITLE
Support for Yubikey 5C

### ISSUE THREAD

**Issue by kt-git** [pallotron/yubiswitch#109]
Having recently moved to a Macbook Pro (i9), I also transitioned to a Yubikey 5C due to the ports all being USB-C on the laptop itself.  This project was mentioned to me because of the use case problem of having this Yubikey with it's touch points on the side, and needing to touch those to pull out the Yubikey because of how snug these are in the usb-c port.

Bottom line, I've experienced that even after plugging in the Product and Vendor id's for my device, it seems not to respect being disabled.  While I won't make assumptions on whether it should work or shouldn't, it did make me wonder if the fact only the Neo and Nano are explicitly supported that it's because the 5c is NOT supported.  

If that's the case, I think adding support for the Yubikey 5C would be beneficial to people on laptops without USB-A ports.

**Comment by pallotron** [comment]
I have an M1 pro laptop now, with a usb-c yubikey. and i can't repro this problem. it is supported.
please try the 0.14 version.
![5E4172B5-3AE0-4845-83B7-232CDCC532B2_1_102_a](https://user-images.githubusercontent.com/508703/192975960-e810f753-f9b4-4695-9545-ec9bc368b5a9.jpeg)
