### ISSUE TITLE
eieecchrvjhbgbgnjftcbkefbcghkttelnelincbkjbk

### ISSUE THREAD

**Issue by lopeng** [pallotron/yubiswitch#111]

**Comment by stevenharman** [comment]
Unsure if this is the perfect Issue, or perfect troll. Maybe both?

![tenor-182940703](https://user-images.githubusercontent.com/48658/187535333-70fffcb0-423d-4204-9a07-92ef38053fa3.gif)

**Comment by AutomationD** [comment]
@lopeng Could you please please provide some description, for instance I usually format it like this:
# cccbcsdookeljhhjrjeicftuggggldecnknkehufn: 
```
cccbvvcfcjjjjrluiiviikijbbfjggdkiicreuxgdkeereddtih
```

**Comment by pallotron** [comment]
i mean, it is not fun to spam my mailbox with this trolling. but ok

**Comment by AutomationD** [comment]
> i mean, it is not fun to spam my mailbox with this trolling. but ok

My apologies, @pallotron. Thank you for an amazing tool!
