### ISSUE TITLE
App is not notarized

### ISSUE THREAD

**Issue by davidrothera** [pallotron/yubiswitch#116]
Beginning in 10.15 all software is checked by Apple for malicious code however to do this the binary has to be uploaded to Apple as well as adhering to a strict set of requirements.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

Opening this as an issue for visibility, at the moment the app and the disk image are signed however they will still show warnings when running.

**Comment by davidrothera** [comment]
So the unfortunate news at the moment is there is no easy fix, enabling "hardened runtime" stops us being able to capture HID events and this "hardened runtime" is a requirement of notarizing.

This might have to wait until if/when we can pivot to using DriverKit (https://developer.apple.com/system-extensions/) however this would likely be a substantial rewrite but might also mean we can kill the privileged helper.

**Comment by pallotron** [comment]
might as well rewrite it in swift to see if I dislike it the same as objective-C :D

**Comment by davidrothera** [comment]
> might as well rewrite it in swift to see if I dislike it the same as objective-C :D

Yeah that is my thought, if we're going to have to burn a core part of it to the ground we might as well go full Swift and SwiftUI 😂

The only PITA part seems to be that the DriverKit profile is now getting into ownership as it would be granted to my developer account and make building harder for others but we can address that later on.

**Comment by davidrothera** [comment]
Fixed in v0.15
