### ISSUE TITLE
YubiSwitch not disabling Yubikey nano on macOS 12.6

### ISSUE THREAD

**Issue by jin-ds** [pallotron/yubiswitch#118]
Hi there,

My Yubikey is no longer being blocked by YubiSwitch. I have installed v0.15 and re-adding accessibility, re-adding the key, quit and reopen YubiSwitch and restart MBP is not solving the issue.

The product ID and vendor ID have been checked about 5 times now, and it was working for about 2 weeks now.

I'm thinking this has something to do with the accessibility permission, but I could be wrong (and don't know how to verify that).

I downgraded back to v0.14 after, but the issue persists.

Please let me know if additional information is needed, thanks!

**Comment by davidrothera** [comment]
Did you have a version older than 0.14 or 0.15 installed prior perhaps? I have a feeling the helper tool isn't being updated with the new version which is now signed with a different certificate for communication authentication.

I'll try and reproduce this today. can you try and follow the uninstall instructions on the README to fully remove the helper and then install 0.15 fresh.

**Comment by jin-ds** [comment]
Hi David,

I had indeed an older version recently, so that could be it!

I followed the uninstall steps, but the issue remains.

One thing I noticed is that it remembered my config, so is it possible there is some caching happening?

**Comment by davidrothera** [comment]
Did it ask you for an admin password upon startup for installing the helper?

**Comment by jin-ds** [comment]
No, it did not. I remember doing it before, but not with the upgrade, so it could be the helper!

**Comment by davidrothera** [comment]
After following the instructions there should be no helper present at the end. If you run `ls /Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper` does it show no file found?

The helper is installed/blessed upon startup so once removed and then re-run it should ask for admin password to install the helper.

Your settings are stored in a different place and are not removed as part of the uninstall process and so your settings being preserved is somewhat expected.

**Comment by davidrothera** [comment]
Yes the instructions need updating along with fixing the updating of the helper.

Thanks for the confirmation its working again.
