### ISSUE TITLE
Sequoia: System Setitngs=>General=>Login Items & Extensions=>Allow in the Background references "Supratude Limited" without any indication that this is related to yubiswitch

### ISSUE THREAD

**Issue by rbergman18** [pallotron/yubiswitch#133]
Ideally this should be changed to reflect that the background item is Yubiswitch so the LaunchDaemon isn't disabled due to lack of knowledge.

**Comment by Cloning4659** [comment]
oooh so that's where supratude came from

**Comment by davidrothera** [comment]
Yes this is my developer certificate.

Unfortunately it's not something which can be changed and therefore the only way to make it clearer would be to set up a legal entity for YubiSwitch and create a business developer account under that entity.

**Comment by rbergman18** [comment]
It doesn’t need to change. Just put it in the readme or something so it’s
not an unknown startup file which could be confused for malware.

**Comment by davidrothera** [comment]
This is now added to the README. Thanks @rbergman18
