### ISSUE TITLE
0.17 release is not notarized

### ISSUE THREAD

**Issue by wlonkly** [pallotron/yubiswitch#136]
Just installed 0.17 on MacOS 14.7 (yay, no more giant icon!) and had to go through the "Apple cannot scan this for malware" dance, for both opening the dmg and for running the app. 

I see in the 0.15 and 0.16 release notes that you notarized it then, so thought I'd mention that the latest release seems to not be notarized.

**Comment by davidrothera** [comment]
Thanks for raising this. It had been submitted but it looks like it was for a prior build for some reason. I'll try and fix this for the existing v0.17 and if not then put out a new version later today.

**Comment by davidrothera** [comment]
@wlonkly this should be resolved now. Please confirm.

**Comment by wlonkly** [comment]
Yep, all good now, thanks!
