### ISSUE TITLE
I get "Can't find YubiKey. Check if it's plugged in then retry." although the YubiKey is plugged in

### ISSUE THREAD

**Issue by gabsong** [pallotron/yubiswitch#25]
I get "Can't find YubiKey. Check if it's plugged in then retry." although the YubiKey is plugged in. Can't seem to find a way to troubleshoot, even after the following:

- Reinstall the Yubiswitch app
- Removing, inserting the YubiKey
- Rebooting the system

**Comment by pallotron** [comment]
I am re-designing things a bit, will see if i can still repro this when I am done.

**Comment by bmorgenthaler** [comment]
I'm getting the same thing with my YubiKey Neo-n.  I've tried with both the packaged version and built from src and it was failing with both.  What I tracked it down to was the mode that the Neo-n was in.  If it's in just OTP mode it works as expected.  If it's in OTP+CCID (so GPG keys can be stored on it) then it get's the cannot be detected.

OS X: 10.10.3
YubiKey Neo-n: 3.3.0

**Comment by eriknomitch** [comment]
:+1:  Also running into this issue but my Yubikey is OTP (Slot 1) Static Password (Slot 2).

**Comment by aaronbwcollins** [comment]
Same. Neo-n with OTP.

**Comment by isokrates** [comment]
Having the same issue with my Nano - can't get it to work at all :(

**Comment by indolering** [comment]
I've tried manually specifying the ProductID and switching connection modes with the NEO manager.  Let me know if you need a sample device.

**Comment by pallotron** [comment]
I've committed a few changes that might help here, if you are Xcode developer please clone my repo and compile the app and try it, and let me know if it solves the issues.
Otherwise wait until I distribute a new DMG file.
The new design decouples the logic that interacts with the usb device from the main app, that logic is moved into a daemon with root privileged, communication between main app and daemon is done via XPC. (you are going to be asked to enter your user password to be able to install the helper daemon).

**Comment by pallotron** [comment]
have you got a chance to try 0.9?

**Comment by isokrates** [comment]
Yep - it doesn't work, I'm afraid - in both enabled and disabled mode I can still use the Yubikey :(

**Comment by pallotron** [comment]
Even with 0.9 version?

**Comment by indolering** [comment]
@pallotron I can compile and give it a shot, but I got it working with the older version.

Are you sure people aren't just having trouble with the product ID?

**Comment by isokrates** [comment]
Even with 0.9. I downloaded the .dmg, moved the app to Applications, entered my password to install the helper, then got a message saying the Yubikey was disabled. I pressed the key and got the code. I then tried enabling it, and it still worked, then disabling it again - and it still continued to work.

My settings have ProductID 0x0010 and VendorID 0x1050. I have a Yubikey Nano. Does that sound correct? Anything else I can try?

**Comment by pallotron** [comment]
:(
I dunno, ran out of ideas, I have a NANO too and my settings are as follow:

![image](https://cloud.githubusercontent.com/assets/508703/9437941/0b75e282-4a52-11e5-973a-b3a4f7185a72.png)

try this:
- quit `yubiswitch`
- open terminal and run `sudo pkill -9 -f yubiswitch` (this should kill both helper and process)
- delete application settings (multiple commands before I change the bundle id in the past and you might have crap still around):
```
$ defaults delete com.pallotron.yubiswitch
$ defaults delete pallotron.c1d406f.yubiswitch
$ defaults delete pallotron.yubiswitch
```
- reboot just in case
- and retry to start the app, make sure settings are correct in preference window.

hope that helps

if not please see if you have anything fishy in /var/log/system.log (grep for yubiswitch maybe)

**Comment by indolering** [comment]
I [posted on the Yubico forum](http://forum.yubico.com/viewtopic.php?f=8&t=2009) requesting a free NEO-N for development purposes, no response.  I can pitch in if need be.

**Comment by pallotron** [comment]
This issue is getting very confusing, it's difficult to understand if it's really only one problem or multiple ones... anything against closing this? you can open separate ones for your specific problem if it needs be.

**Comment by indolering** [comment]
@pallotron Latest DMG works for me, I have a relatively new NEO-n.

@isokrates Did you lookup your USB Product ID using system information?  That's the only way to know which product ID is correct.  Also, can you post your NEO-n's firmware version?  Finally, did you clear your contrab of the YubiSwitch line?

**Comment by pallotron** [comment]
ok guys I'm going to close this, you can still discuss it in this thread even if the case is closed :)

**Comment by isokrates** [comment]
Hi guys,

@indolering - not sure how to do this - can you explain?
@pallotron - still having the same problem, but perhaps the steps suggested above will fix it...

**Comment by indolering** [comment]
@isokrates 
WRT the product ID: Open "System Information" -> hardware -> USB.  You should be able to find a "Yubikey NEO ..." in the USB device tree.  Click on it and you will find the Product ID.  The product ID should be between 0x0110-0x0116.  Punch that number into the YubiSwitch preference panel.

WRT the crontab entry, did you ever create a crontab entry?  If so, then clear it.  If not, then don't worry about it.

**Comment by isokrates** [comment]
Thanks so much for that - I must have missed that step somewhere. Punched
in 0x114 and it now works marvellously. Thank you both very much indeed! :)
