### ISSUE TITLE
Yubiswitch may (unintentionally) defeat 2FA due to "buffered" Yubikey presses

### ISSUE THREAD

**Issue by anirudhvr** [pallotron/yubiswitch#29]
This is a great idea (and execution) but I fear there's a big issue with the way the device suspension currently works. When the device is disabled, touching the device lights up the yubikey (indicating activation) and the lights stay on until we enable the device on Yubiswitch. However, when enabled, the *buffered* OTP is immediately entered without needing to touch the key again. 

So a malicious program could, entirely with software actions, defeat the 2FA by checking for and enabling the device on Yubiswitch to read the "buffered" OTP without needing a human. 

Any thoughts on this? Ideal case would be to disable the Yubikey entirely while it's disabled on Yubiswitch, such as by resetting the device or disabling the USB port entirely (e.g., perhaps using http://github.com/libusb)?

**Comment by pallotron** [comment]
I agree with your concern, next version I am currently working on (alas
don't have much time to commit to it these days) won't have this problem.

**Comment by pallotron** [comment]
try to download and use release 0.9.

**Comment by anirudhvr** [comment]
Works great; Thanks!!

**Comment by pallotron** [comment]
Nice!
