### ISSUE TITLE
Lock computer when yubikey is removed

### ISSUE THREAD

**Issue by pallotron** [pallotron/yubiswitch#3]

**Comment by pallotron** [comment]
this seems to be what I want:

http://stackoverflow.com/questions/1976520/lock-screen-by-api-in-mac-os-x

**Comment by bmorgenthaler** [comment]
I would LOVE this, I'm using TokenLock currently to perform this function and though while it works having everything in one application would be nice.

**Comment by pallotron** [comment]
Yeah I am working on it :)

**Comment by pallotron** [comment]
This has been implemented in 08649980bbb38255067d4c30cac8726430235a11 :)
