### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by 3on** [pallotron/yubiswitch#30]
I feel like a double click option might help many misscliks.

**Comment by pallotron** [comment]
I don't get what you mean, can you elaborate please?

**Comment by 3on** [comment]
Most of the time I miss-click on my yubikey is when I move my laptop.
I wonder if just disabling the yubikey until there is a clear second clear click would probably remove most of the missclick.

**Comment by pallotron** [comment]
this is exactly what the application solves, when you press the yubikey, if everything is configured properly, and the key is marked disabled, nothing should happen. only when you use the hotkey or click on "Enable yubikey" it will work.
you should check your settings, make sure you use proper productID and vendorID for your yubikey.

you can easily find those values opening `/Applications/Utilities/System Information.app/`, then click on `System report...` -> `USB` -> look for your yubikey and then look for Product ID and VEndor ID.

hope this helps.

**Comment by 3on** [comment]
I meant clicking the key itself twice and then with a timer re-disabling it.

**Comment by pallotron** [comment]
ok, I can't make that working, because I can't change the way the hardware works itself, ask Yubico people :D

**Comment by 3on** [comment]
I wondered if it was possible to catch the key input and ignore it the first time.

**Comment by pallotron** [comment]
I don't know, I don't think you need any double click to be honest, I just hit cmd-option-y to enable the yubikey and then touch it. after 10s the yubike will be disabled again. and even if you touch it won't flush any character :)
