### ISSUE TITLE
0.9 release won't start

### ISSUE THREAD

**Issue by borgstrom** [pallotron/yubiswitch#31]
I just downloaded the 0.9 release, which was released a couple of hours ago.

When opening the app nothing happens, and when run from a termain I get:

```
#503 ❯❯❯ /Applications/yubiswitch.app/Contents/MacOS/yubiswitch -h
2015-08-17 15:41:31.420 yubiswitch[21984:442689] Unable to load nib file: MainMenu, exiting
```

**Comment by borgstrom** [comment]
PS.  I'm on MacBookPro11,1 running OS X 10.10.4 (14E46)

**Comment by pallotron** [comment]
oh crap, ok, let me update the release now. sorry about it.

**Comment by pallotron** [comment]
ok I've uploaded a new DMG file. give it a try, I just tried it on my machine and it seems to work.
