### ISSUE TITLE
Enable Yubikey when system locks/sleeps

### ISSUE THREAD

**Issue by bmorgenthaler** [pallotron/yubiswitch#37]
I'm using my Yubikey NEO-n as part of multi-factor authentication for my Mac (https://www.yubico.com/wp-content/uploads/2015/04/YubiKey-OSX-Login.pdf). Unfortunately when Yubiswitch disables the NEO-n it no longer works for login.

It would be nice if Yubiswitch had a hook into the system to re-enable the Yubikey whenever the system goes into screensaver, locks or sleeps.

**Comment by pallotron** [comment]
I'll look into it.

**Comment by pallotron** [comment]
ok this is pushed, need to make a new release, will do soon, watch this space! :-)
alternatively if you have xcode and an apple developer account you can `git clone` and compile `HEAD` yourself.
thanks for opening the issue.

**Comment by pallotron** [comment]
v 0.11 is out :)
