### ISSUE TITLE
"Failed to bless helper" when starting

### ISSUE THREAD

**Issue by jacobian** [pallotron/yubiswitch#38]
I've just upgraded to 0.10, and I'm getting this when trying to start yubiswitch:

![](https://dl.dropboxusercontent.com/s/0rhjmxdesr0npuq/2015-08-27%20at%209.24%20AM.png)

I'm on OSX 10.10.4.

**Comment by pallotron** [comment]
try this:
- quit app
- ` sudo pkill -9 -f com.pallotron.yubiswitch.helper`
- restart app

what's in `/var/log/system.log'?

**Comment by pallotron** [comment]
also `rm /Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper`

**Comment by pallotron** [comment]
Oh man I can repro this... investigating.... Use 0.9 in the meantime.

**Comment by jacobian** [comment]
FTR:

```
$ sudo pkill -9 -f com.pallotron.yubiswitch.helper

exited 1 ~
$ sudo rm /Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper
rm: /Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper: No such file or directory
```

0.9 appears to install correctly though, so that works!

**Comment by pallotron** [comment]
can you try killing and removing everything again, then download dmg again (i've just uploaded a new version) and let me know?

**Comment by jacobian** [comment]
:+1: that seems to have done the trick, working now!
