### ISSUE TITLE
Broke Support for 10.9

### ISSUE THREAD

**Issue by indolering** [pallotron/yubiswitch#39]
YubiSwitch .10 and .11 releases won't open in OS X 10.9.  Not a *major* problem but it would be nice to have support for it while until the bugs in 10.11 get worked out.  I skipped 10.10 due to DNS issues that are (supposedly) fixed in 10.11....

Close if not feasible.

**Comment by pallotron** [comment]
alright I will build you a dmg for OSX 10.9

**Comment by pallotron** [comment]
try `yubiswitch_0.11_osx10.9.dmg` in https://github.com/pallotron/yubiswitch/releases/tag/v0.11_enable_yubikey_when_screen_locked
