### ISSUE TITLE
Command line enable/disable

### ISSUE THREAD

**Issue by ross** [pallotron/yubiswitch#40]
Not a huge deal, but I'd like to be able to enable/disable the yubikey from the command line. It'd allow me to create an alias to enable it before ssh'ing in to a server where I'll be using it as part of the auth flow. I can obviously hit the key-binding to enable it as I do now, but I'd save one more step. Feel free to close if it'd be a pain to do or you don't think it makes sense. Thanks for the app regardless.

**Comment by ross** [comment]
My bad, just found the section of the Readme with this info. Didn't see it when I first scanned it.

**Comment by pallotron** [comment]
:+1:
