### ISSUE TITLE
Yubiswitch doesn't work until I enable then re-disable the yubikey

### ISSUE THREAD

**Issue by wjohnson5** [pallotron/yubiswitch#42]
I have a yubikey nano. Often when I wake from sleep or unplug and replug the yubikey, I can still accidentally trigger the yubikey even though yubiswitch says the yubikey is 'disabled'. I have to enable and re-disable the yubikey so that yubiswitch works. It's as if yubiswitch doesn't detect the yubikey is plugged in.

**Comment by pallotron** [comment]
Do you have the "Enable the yubikey when system locks/sleeps" option? if so, turn it off.

**Comment by wjohnson5** [comment]
That doesn't seem to have fixed it.

**Comment by NeMO84** [comment]
Same issue here :(

**Comment by dougbateman** [comment]
I am having the same problem.  I'm a programmer, is there any way I can help with debugging?

**Comment by dougbateman** [comment]
I was able to fix it by setting the correct Product ID.  See this issue here: https://github.com/pallotron/yubiswitch/issues/45
