### ISSUE TITLE
YubiKey doesn't disable

### ISSUE THREAD

**Issue by kennetham** [pallotron/yubiswitch#45]
After enabling YubiKey, disabling it doesn't take effect.

'Lock computer after YubiKey is removed' doesn't take effect either.

**Comment by remmelt** [comment]
Same here

```
ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep Product
    |     "idProduct" = 0x407
    |     "iProduct" = 0x2
    |     "USB Product Name" = "Yubikey 4 OTP+U2F+CCID"
```

Which values should go in which fields?

**Comment by pallotron** [comment]
![image](https://cloud.githubusercontent.com/assets/508703/11613332/4e3d71e2-9c15-11e5-80ca-a7f63ff569cb.png)

in the preference window, as per screenshot above.

**Comment by remmelt** [comment]
I understand where to put the IDs, but it still doesn't work.





---

**Comment by pallotron** [comment]
I have no idea, it works for other people with different product/vendor IDS. patches are welcome :)
Have you tried to quit and restart the application when you change the settings?
How am I supposed to troubleshoot w/o logs? Do you see anything fancy in /var/log/system.log related to yubiswitch?

**Comment by MartinRogalla** [comment]
Didn't work for me earlier. Restarted yubiswitch after specifying the productid, now works. Thanks, this is great! :)

**Comment by ndynan** [comment]
Had the same issue you need to set the productid in prefences 

Run in terminal and get the product ID:
$ ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep Product

Run the following to get the VendorID
$ ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep Vendor
