### ISSUE TITLE
Yubiswitch Not Working on OS X El Capitan

### ISSUE THREAD

**Issue by cbs38** [pallotron/yubiswitch#47]
On Mac OS X El Capitan (10.11.x) I can enable/disable via the Yubiswitch UI and it has no effect. Is this a known issue?

**Comment by pallotron** [comment]
it  works for me.

![image](https://cloud.githubusercontent.com/assets/508703/12722894/f3859f24-c8fe-11e5-8880-e6405235f1f8.png)

**Comment by cbs38** [comment]
Odd. Did you have to configure anything on the system side (Accessibility, Configuration, etc.) to get it working. I have tried almost everything I know to no avail.

**Comment by pallotron** [comment]
nope, just make sure you get producID/vendorID configured properly. restart the app just incase, and kill the helper too, instructions are in `README.md`

**Comment by cbs38** [comment]
No joy. IDs are set and app restarted. Still no effect.

**Comment by pallotron** [comment]
what's the output of this command in your terminal?

```
$ ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep Product
```

**Comment by pallotron** [comment]
also, paste what happens in `/var/log/systems.log` when you try to enable/disable the key

```
# tail -f /var/log/system.log | grep -i yubi
```

**Comment by cbs38** [comment]
```
$ ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep Product
    |     "idProduct" = 0x407
    |     "iProduct" = 0x2
    |     "USB Product Name" = "Yubikey 4 OTP+U2F+CCID"
```

```
Feb  1 14:53:00 ori-c02qp19h com.pallotron.yubiswitch.helper[6176]: Received message. idProduct: 16, idVendor: 4176, action: 1
Feb  1 14:53:13 ori-c02qp19h com.pallotron.yubiswitch.helper[6176]: Received message. idProduct: 16, idVendor: 4176, action: 0

```

![yubiswitch_preferences](https://cloud.githubusercontent.com/assets/16669044/12729284/f214431c-c8f3-11e5-8dad-f90166f6491c.png)

**Comment by pallotron** [comment]
so you got "idProduct" = 0x407 and  "iProduct" = 0x2..... and then you don't have the same in the preferences.... you must copy those values in the preferences..... I thought that was clear in the instructions....

**Comment by pallotron** [comment]
copy productID and vendorID from the ioreg command to the preferences, and restart the app just in case. i would also kill the helper to be sure:

```
sudo pkill -9 -f com.pallotron.yubiswitch.helper
```

**Comment by cbs38** [comment]
Everything seems to be working this morning. The previous screenshot was to indicate the settings weren't being saved through application stop/start (the instructions are clear-ish enough). Not killing the helper service was likely the cause I'm assuming. Great tool, thank you for the help.

**Comment by pallotron** [comment]
np, enjoy
