### ISSUE TITLE
Document how to uninstall

### ISSUE THREAD

**Issue by candlerb** [pallotron/yubiswitch#48]
I tried yubiswitch and it didn't work for me (Yubikey 4 Nano, OSX 10.9.5) - setting to either 'disabled' or 'enabled', touching would still generate the OTP code.

So I want to uninstall but it's not clear how. Obviously I've removed the app from the Applications folder, and after a reboot the daemon is no longer running.

I had to give it root permissions during installation. Has it configured something which needs to be undone?

I see that `/Library/LaunchDaemons/com.pallotron.yubiswitch.helper.plist` is still present. And this in turn points to `/Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper`. So I've removed those now. Is there anything else to be done?

There is what looks like a crash log in `/Library/Logs/DiagnosticReports/com.pallotron.yubiswitch.helper,VBoxNetDHCP,VBoxSVC,VBoxXPCOMIPC_2016-03-14-194426_Brians-MacBook-Air.shutdownStall`

**Comment by pallotron** [comment]
This should work:

```
# pkill -f com.pallotron.yubiswitch.helper
# launchctl stop com.pallotron.yubiswitch.helper
# launchctl remove com.pallotron.yubiswitch.helper
# launchctl list | grep -i yubi (to make sure it's not there)
# rm /Library/PrivilegedHelperTools/com.pallotron.yubiswitch.helper
# rm /Applications/yubiswitch.app/
```

Probably also remove it from the Log Items in your System Preferences.
Let me know if this works.

**Comment by pallotron** [comment]
And yes, application installs an helper daemon that runs under root privileges to get old of the HID device.

**Comment by candlerb** [comment]
Thanks!

**Comment by pallotron** [comment]
Added to README.md thanks.\
