### ISSUE TITLE
Security check – "yubiswitch is trying to install a new helper tool"

### ISSUE THREAD

**Issue by lorensr** [pallotron/yubiswitch#49]
What's this for? Came up after restarting today, latest OS X. Thanks!

![image](https://cloud.githubusercontent.com/assets/251288/15490207/32b5c5ce-2134-11e6-998b-323d932aa572.png)

When I hit cancel, I get:

![image](https://cloud.githubusercontent.com/assets/251288/15490213/3b89720e-2134-11e6-9627-2f2a52ec39e4.png)

**Comment by pallotron** [comment]
It's explained in the README.md in the homepage of the project.........
On Tue 24 May 2016 at 03:18, Loren Sands-Ramshaw <notifications@github.com>
wrote:

> What's this for? Came up after restarting today, latest OS X. Thanks!
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/251288/15490207/32b5c5ce-2134-11e6-998b-323d932aa572.png>
>
> When I hit cancel, I get:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/251288/15490213/3b89720e-2134-11e6-9627-2f2a52ec39e4.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pallotron/yubiswitch/issues/49>
>
-- 

Angelo "pallotron" Failla - pallotron(at)[freaknet.org|gmail.com]

W3: http://www.angelofailla.com

Blog: http://blog.angelofailla.com

FB: https://www.facebook.com/pallotron

TW: https://twitter.com/pallotron

GPG Key ID: 89450920 available @ pgp.mit.edu

GPG FingerPrint: 0DE8 DB22 538E D6B9 8784  83E5 1BEA 7D5C 8945 0920

**Comment by pallotron** [comment]
privileges which contains the logic to grab the USB HID interface, the main application talks to this daemon via XPC calls. When you start Yubiswitch for the first time it will ask for your user's password, this is expected to install the helper before mentioned.

**Comment by pallotron** [comment]
Sorry copy paste fail:

Yubiswitch installs an helper daemon with root privileges which contains the logic to grab the USB HID interface, the main application talks to this daemon via XPC calls. When you start Yubiswitch for the first time it will ask for your user's password, this is expected to install the helper before mentioned

**Comment by lorensr** [comment]
Thanks. Sorry, didn't come up in my google or issue search. Weird that it comes up months after installation.
