### ISSUE TITLE
Power off USB device instead of sending configuration(0)

### ISSUE THREAD

**Issue by pallotron** [pallotron/yubiswitch#5]
Instead of sending configuration(0) to the yubikey try to see if there is a way (in IOKit?) to power off a device?

**Comment by mathomp4** [comment]
@pallotron If you leave the key permanently plugged in (as I do), are you able to turn off the led? I know it's only my situation, but the way things turn out, the Yubikey faces me at night in bed...so I get a nice green laser all night if I forget to cover it. :)

**Comment by pallotron** [comment]
No I didn't find a way to do it :(

**Comment by pallotron** [comment]
I am working on a commit that should solve this. Stay tuned!

**Comment by indolering** [comment]
Not sure if this is the best option anymore, I would like to keep U2F and CCID capabilities while disabling OTP and Static Password....

**Comment by pallotron** [comment]
I've committed a few changes that might help here, if you are Xcode developer please clone my repo and compile the app and try it, and let me know if it solves the issues.
Otherwise wait until I distribute a new DMG file.
