### ISSUE TITLE
Yubico vs YubiKey

### ISSUE THREAD

**Issue by TomAtYubico** [pallotron/yubiswitch#51]
https://github.com/pallotron/yubiswitch/blob/master/README.md

> **Yubikey** is the producer of the Yubikeys: an hardware authentication device, designed to provide an easy to use and secure compliment to the traditional username and password.

**Yubico** is the produce of the Yubi**K**eys

**Comment by pallotron** [comment]
Pull Request are welcome :D

**Comment by pallotron** [comment]
fixed.
