### ISSUE TITLE
Please document support for YubiKey 4 Nano

### ISSUE THREAD

**Issue by SueHeim** [pallotron/yubiswitch#52]
Please document how to add YubiKey 4 Nano. The default vendor ID and product ID info are as follows:
'0x1050', '0x0407', 'Yubico Yubikey 4 OTP+CCID+U2F'

This is our current nano-sized YubiKey offered for sale.

Thanks!

**Comment by pallotron** [comment]
There is a generic method explained in the `README` already in this section: https://github.com/pallotron/yubiswitch#how-to-find-productid-and-vendorid
