### ISSUE TITLE
kbkrbktigjfvdkvh

### ISSUE THREAD

**Issue by doriable** [pallotron/yubiswitch#53]

**Comment by pallotron** [comment]
I don't think this is fun.

**Comment by doriable** [comment]
@pallotron Sorry, it was a legit accident. I was actually reviewing the issue regarding yubiswitch not working when the device powers down and it went off. Sorry! :(

**Comment by pallotron** [comment]
yeah sure.... bullshit. :D

**Comment by doriable** [comment]
@pallotron haha, I wish I was clever enough to think of that. in all honesty though, I've tried to restart the program, triple checked the config, and it's still going off :( it was working when I first installed it 3 days ago, but I restarted my computer yesterday and it has stopped working. I actually wanted to look into everything before opening up an actual issue, but this might as well be as good a time as any to bring it up.
