### ISSUE TITLE
Control delay

### ISSUE THREAD

**Issue by peterg79** [pallotron/yubiswitch#58]
Great app, I love it! Wish there is a setting to control the delay of N seconds before it is activated and starts spitting out the random strings.

**Comment by pallotron** [comment]
the whole point of the application is that the key is always disabled, to enable it you have to hit the hotkey configured, then you can touch the yubikey to produce the random string, and then, after a configurable amount of time, it will disable it.

I am not sure what you are going to gain with your request.
closing, reopen if you think I didn't understand what you mean.
