### ISSUE TITLE
Yubiswitch not re-enabling YubiKey on Lock in 10.2.2 Sierra

### ISSUE THREAD

**Issue by bmorgenthaler** [pallotron/yubiswitch#59]
macOS: 10.12.2
Yubiswitch: 0.12

When calling Lock from Alfred or from HotCorners yubiswitch doesn't re-enable to YubiKey to allow for unlock.  Remoting into the system with SSH allows for calling osascript KeyOn or to kill yubiswitch which then allows for successful logon.

**Comment by pallotron** [comment]
weird, I can't repro. I am too on 10.12.2 (I think there is a typo in your title/summary) and 0.12.
I just tried with hotcorner and it works.

Do you have "Enable Yubikey when system locks/sleeps"? Like this:

![image](https://cloud.githubusercontent.com/assets/508703/21289723/2b850948-c49c-11e6-8c2f-1b0f5c709b04.png)

**Comment by pallotron** [comment]
it works with hotcorner and not with Alfred -> lock.
it works with alfred -> screensaver

**Comment by pallotron** [comment]
See instructions on https://github.com/pallotron/yubiswitch#running
The way I use it is by forcing request of password immediately upon sleep/screensaver.
Alfred -> Lock maybe not supported. Patch/PRs welcome.

![image](https://cloud.githubusercontent.com/assets/508703/21289742/89a6e168-c49c-11e6-9c07-8d1d7e49274a.png)

**Comment by bmorgenthaler** [comment]
Yep 10.12.2, fat fingered it.

Hmm, so my screensaver isn't configured to require password right after sleep unfortunately (Due to some bug in JAMF deployment I'm told).

However I did put Keychain Access in my menu bar and locked through that and Yubiswitch worked.  I don't know what method Alfred calls with lock, I'll have to did into that.

**Comment by pallotron** [comment]
ok I will close this ticket.
