### ISSUE TITLE
ikivvvidtnvfcue

### ISSUE THREAD

**Issue by indythegeek** [pallotron/yubiswitch#63]

**Comment by pallotron** [comment]
if you think this is original you are not :D

**Comment by indythegeek** [comment]
Hilariously, I think that this was opened by pushing OTP with the browser in focus. Thanks to this code, this shouldn't happen again.

**Comment by indythegeek** [comment]
Oh, and look, it looks like others have accidentally opened tickets with their OTPs...

**Comment by pallotron** [comment]
that's why I said you weren't the only one...

**Comment by indythegeek** [comment]
Well, the string is unique! Or at least that's what I'm told...

**Comment by jessereitsma** [comment]
@pallotron It's not a troll, if you at the issue page, and hit the `c` key, you will be redirected to the create new issue page.
And it happens that the first key of your OTP is the `c`, followed by your OTP and the return key.
So those people are not trolling you, they are pushing their OTP button at the issue page :)

**Comment by pallotron** [comment]
jesus, then if it happens this often this tool is really helpful :D

**Comment by indythegeek** [comment]
It isn't that it happens that often. I is just that there is a high likely hood that people are testing the OTP button over and over again while looking at the issues page because they have just installed the software and are trying to get it to work.
