### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by danielpops** [pallotron/yubiswitch#64]
I'm on Sierra 10.12.3, trying this out for the first time. It doesn't seem to work, in that my yubikey is never actually disabled, despite the UI telling me that it should be.

Is this a known issue? What kind of logs etc. can I provide to help investigate the issue?

**Comment by boopathi** [comment]
Same version of OSX. Experiencing the same issue - The UI says it's disabled but it is not.

**Comment by danielpops** [comment]
Oops! I should have RTFM'd. Thanks @boopathi! That works well!! And now I can stop yubisneezing in IRC all day! :)
