### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by kterusaki** [pallotron/yubiswitch#68]
I've edited the preferences to reflect the right product id and vendor id as instructed. That worked, but recently it has stopped working. I'm on iOS 10.12.5

**Comment by jessereitsma** [comment]
Same on 10.12.4 with GPG Suite 2017.1 (2002)

![image](https://user-images.githubusercontent.com/5758900/31067534-aebff06c-a753-11e7-8973-4b9f54fbe4d8.png)

Since update to latest GPGsuite, Yubiswitch crashes after removing the yubikey.

**Comment by pallotron** [comment]
I don't have spare cycles to check this any time soon. But I will take a look eventually. Please do not reopen the same ticket. open a new one.
