### ISSUE TITLE
Let's have a brew cask for this fine piece of software

### ISSUE THREAD

**Issue by zsol** [pallotron/yubiswitch#69]
It would sure make it easier to keep up-to-date

**Comment by arlolra** [comment]
https://github.com/caskroom/homebrew-drivers/blob/master/Casks/yubiswitch.rb

**Comment by arkon** [comment]
It'd be nice to have this in the README.

**Comment by pallotron** [comment]
I accept Pull Requests :P

**Comment by pallotron** [comment]
cask is there, i don't think cask+yubiswitch users really need this in README :P
they can find shit on their own.
