### ISSUE TITLE
Seems not to work with YubiKey 4C Nano

### ISSUE THREAD

**Issue by stefandeml** [pallotron/yubiswitch#76]
Hello everybody,

using the YubiKey 4C Nano the tool doesn't find the key.
Any chance for a fix?

Best,
Stefan

**Comment by pallotron** [comment]
you need to use the proper ProductID/VEndorID, see instructions in https://github.com/pallotron/yubiswitch#how-to-find-productid-and-vendorid

**Comment by pallotron** [comment]
it' in the known issue section of the homepage:

>  The app's default settings support the Nano. If you have the neo, go into the app's Preferences by clicking on the menu icon, then set the the Product ID to 0x0114 (or whatever your ProductID is).

I guess the 4C Nano has different productID. closing. reopen if that didn't solve it.

**Comment by stefandeml** [comment]
I followed the instructions, see the following screenshot: https://imgur.com/HPoCLfZ

I also don't get an error, but the yubikey still works even when the device is disabled in the tool.

**Comment by stefandeml** [comment]
please re-open

**Comment by stefandeml** [comment]
hello?

**Comment by pallotron** [comment]
Sorry I don't have time to dedicate to this project at the moment. :(
The source code is available for anybody to debug.

**Comment by erikdw** [comment]
FWIW, using `0x407` as the ProductID worked for me with my YubiKey 4C Nano.  I did have to quit & restart the Yubiswitch Toolbar App for the change to come into effect.
