### ISSUE TITLE
Touchbar support

### ISSUE THREAD

**Issue by kwm4385** [pallotron/yubiswitch#77]
What a life changer this project is! 😆 
The only suggestion I have is it would be great to have an option to add an icon to enable the yubikey in the Macbook Pro touchbar rather than the menu.

**Comment by pallotron** [comment]
thanks for your suggestion. I don't have much time to dedicate to this project at the moment but I will consider this for the future.

**Comment by pallotron** [comment]
I am closing this, if you care and have the time send a PR. I don't have time to dedicate to this project unfortunately :(
