### ISSUE TITLE
MBP on High Sierra not locking when Yubikey Nano removed

### ISSUE THREAD

**Issue by rca** [pallotron/yubiswitch#78]
Hello, thanks for making this tool!

I'm on Mac OS High Sierra v10.13.4 and have a [YubiKey 4 Nano](https://www.yubico.com/product/yubikey-4-series/#yubikey-4-nano).  The feature to lock the computer when the yubikey is removed is not working.

I'm using Yubiswitch 0.12:

![image](https://user-images.githubusercontent.com/53537/39999092-143abfdc-5756-11e8-8470-7f1c45d62171.png)

In the [Mac Console](https://support.apple.com/guide/console/welcome/mac) I see the following message when I remove the YubiKey:

```
AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.
```

Using `ioreg` I see the following:

```
$ ioreg -p IOUSB -l -w 0 -x | grep Yubikey -A10 | grep -e Product -e Vendor
          "idProduct" = 0x407
          "iProduct" = 0x2
          "USB Product Name" = "Yubikey 4 OTP+U2F+CCID"
          "USB Vendor Name" = "Yubico"
          "idVendor" = 0x1050
```

And I've changed the product id in the settings accordingly:

<img width="626" alt="screen shot 2018-05-14 at 8 59 00 am" src="https://user-images.githubusercontent.com/53537/39998761-169e650e-5755-11e8-82ed-442809f0f128.png">

Any additional info I can provide to help get this fixed?

Thank you!

**Comment by femiagbabiaka** [comment]
@rca bit old, but you added an extra character onto your product ID. When I use `0x407`, the software works again.

**Comment by femiagbabiaka** [comment]
@rca ack, can confirm that doesn't work for me either ATM

**Comment by femiagbabiaka** [comment]
https://github.com/pallotron/yubiswitch/blob/master/yubiswitch.helper/main.c#L55-L59

@rca looks like the code that would do that is commented out -- likely because it doesn't work anymore. I'm not a maintainer, but I'll try to put up a PR in the next few days to fix it. (also to add an uninstall script...)

**Comment by rca** [comment]
I'm going to close this.  A completely fresh install on Mac, plus a reboot seems to work fine! 👍
