### ISSUE TITLE
Option to disable notifications

### ISSUE THREAD

**Issue by rca** [pallotron/yubiswitch#79]
An option to disable Notification Center notifications would be great.  I get a lot of them and, for me, the little green light that shows up in the menubar icon is more than adequate.

Thank you.

![screen shot 2018-05-17 at 9 28 47 pm](https://user-images.githubusercontent.com/53537/40211614-a047090c-5a19-11e8-911b-6eaa0d5ac018.png)

**Comment by pallotron** [comment]
Hi, thanks for opening this issue. However I don't have free time to dedicate to this. This is something I created for my personal consumption which ended up to be pretty popular... I accept PRs though. It shouldn't be that difficult :)

**Comment by chrisellsworth** [comment]
You can disable the notifications from System Preferences:

<img width="780" alt="screen shot 2018-06-15 at 9 09 38 am" src="https://user-images.githubusercontent.com/1240464/41478269-e333a5ea-707b-11e8-94e9-bdc49c93bf53.png">

**Comment by pallotron** [comment]
good suggestion from @chrisellsworth.
closing this.
