### ISSUE TITLE
0.13 DMG is damaged

### ISSUE THREAD

**Issue by thefotios** [pallotron/yubiswitch#80]
I'm able to install `yubiswitch` but when attempting to run, I receive the following error: 
> “yubiswitch” is damaged and can’t be opened. You should move it to the Trash.

I'm not an OSX app developer, but here's some information that might be useful. Let me know if you need anything else.

```bash
> shasum -a 256 ~/Downloads/yubiswitch_0.13.dmg
7b56ad36c11d888f9da6f273ba7c554b38d3f4289ecd030b998189d56100efbd  /yubiswitch_0.13.dmg

> codesign -v -v /Volumes/yubiswitch/yubiswitch.app
/Volumes/yubiswitch/yubiswitch.app: a sealed resource is missing or invalid
file modified: /Volumes/yubiswitch/yubiswitch.app/Contents/Library/LaunchServices/com.pallotron.yubiswitch.helper
```

**Comment by tomvachon** [comment]
Same here, something happened in the packaging

**Comment by pallotron** [comment]
damn... i will retire the release for now. need to find the spare time to look into it when i am off my paying work oncall :D

**Comment by pallotron** [comment]
in the meantime I made it clear in the release page that 0.13 is broken and people should use 0.12 for now.

**Comment by grempe** [comment]
It sure would be nice, after seven months, to have a non-broken release at the top of the releases page. :-)

I'm curious why you didn't remove the bad release instead of marking it as `(broken DON'T DOWNLOAD USE 0.12)`

Cheers

**Comment by pallotron** [comment]
I simply don't want to pay 90 EUR to Apple just to build and sign a new release. Also I don't have the time to dedicate to this project. You can build the dmg yourself with Xcode if you want. I will remeove the 0.13 release from here now.

**Comment by pallotron** [comment]
looks like there is no way in GH to remove a release, this is why I didn't remove it.

**Comment by grempe** [comment]
Understood.

Here's the instructions for release edit/removal.

https://help.github.com/en/articles/editing-and-deleting-releases

Also, for my simple case this solved my issue cleanly:

https://support.yubico.com/support/solutions/articles/15000006440-accidentally-triggering-otp-codes-with-your-nano-yubikey

**Comment by pallotron** [comment]
> Here's the instructions for release edit/removal.
> https://help.github.com/en/articles/editing-and-deleting-releases

thanks! I have done that!
