### ISSUE TITLE
Active Application Whitelist/Rule Engine

### ISSUE THREAD

**Issue by indolering** [pallotron/yubiswitch#9]
Abstractly speaking, the problem YubiSwitch is trying to solve is accidental input into incorrect text fields.  Right now, YubiSwitch offers a rough all-or-nothing approach, but we could get more selective with some sort of rule engine.

The most basic would just be a whitelist of allowed applications where YubiSwitch is on by default. This would be pretty easy to do with AppleScript as it would only require checking frontmost on activation.

You could go even further and detect the windows name, like `Pinentry Mac` for the MacGPG entry window.

Finally, you could even check for the presence of password fields using NSSecureTextField.  However, I don't know how well this would work with non Cocoa applications and I'm betting it would require the accessibility option that allows applications to interact with the GUI directly.

**Comment by pallotron** [comment]
I don't have much time to work on this, if you feel brave submit PR! :)
