### ISSUE TITLE
Not disabling yubiswitch

### ISSUE THREAD

**Issue by calebyoon** [pallotron/yubiswitch#92]
Yubiswitch was working properly until a few days ago. (I think it stopped working after i updated to catalina).

Configurations
Yubiswitch 0.12
ProductID: 0x0407
VendorID: 0x1050

**Comment by antonqiu** [comment]
Same here.

macOS Catalina
Yubiswitch 0.12
ProductID: 0x0407
VendorID: 0x1050

**Comment by ctrl-tom** [comment]
Duplicate of https://github.com/pallotron/yubiswitch/issues/86

**Comment by pallotron** [comment]
try the new 0.14 release
i have your same key (0x0407) and it works
