### ISSUE TITLE
Incorrect toggling behavior with "auto switch off Yubikey" enabled

### ISSUE THREAD

**Issue by cruisercohen** [pallotron/yubiswitch#98]
I've been experiencing a bug with the toggling behavior when "Automatically switch off Yubikey" is enabled.

Reproduction steps:
- Configure with the “Auto switch off yubikey” option
- Enable manually with "Enable Yubikey" or hotkey
    - Yubikey is enabled and works
- Disable manually by unchecking"Enable Yubikey" or using hotkey 
    - Yubikey is disabled and does not emit one time passords
- After 10 seconds the auto-disable happens, which actually re-enables the key (though visual indicator shows disabled)
    - Yubikey is enabled again and will send out one time passwords
    - Note that the toolbar icon remains in disabled grey state even as the Yubikey continues to work

Workaround:
- Manually enable with "Enable Yubikey" or hotkey
    - Yubikey remains enabled, this seems to have "reset" things
- Wait for the auto-disable
    - Yubikey is disabled and will not send out one time passwords
- Never manually disable Yubikey

**Comment by pallotron** [comment]
I tried to repro this, on the new 0.14 that @davidrothera published, and i can't repro, i tried the reproduction steps to the letter and it does not happen to me. closing. please try 0.14 and reopen if you still see the issue.
